name: Update

on:
    schedule:
        - cron: '0 0 */5 * *'
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Download libraries
        run: | 
            curl -L -f https://dl5.oo-software.com/files/ooshutup10/OOSU10.exe > src/DuckOS_Modules/OOSU10.exe
            curl -L -f https://sourceforge.net/projects/sevenzip/files/latest/download > src/DuckOS_Modules/Utils/7zip.exe
            curl -L -f https://sourceforge.net/projects/open-shell.mirror/files/latest/download > src/DuckOS_Modules/Utils/OpenShell.exe
            curl -L -f https://www.nirsoft.net/utils/devmanview-x64.zip > src/DuckOS_Modules/devmanview.zip
            curl -L -f https://www.sordum.org/files/downloads.php?power-run > src/DuckOS_Modules/powerrun.zip
            cd src/DuckOS_Modules/
            sudo unzip -o devmanview.zip
            sudo rm -f DevManView.chm
            sudo rm -f readme.txt 
            sudo rm -f devmanview.zip
            sudo rm -f PowerRun
            cd ..
            cd "Desktop/DuckOS - Post Install Folder/Tools/ProcessExplorer"
            curl -L -f https://live.sysinternals.com/procexp.exe > "Process Explorer.exe"
            curl -L -f https://live.sysinternals.com/autoruns.exe > "!Autoruns.exe"

      # Runs a set of commands using the runners shell
      - name: Commit changes
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions - update modules"
          git add --all
          git commit -m "Update modules"
          git push
